spring:
  application:
    name: acstatistiques

server:
  port: 10010

management:
  endpoints:
    web:
      exposure:
        include: env,health,
          info,metrics,
          loggers,mappings, prometheus
  tracing:
    sampling:
      probability: 1.0

# Configuration du log.
logging:
  level:
    org.springframework.web: INFO # Choix du niveau de log affiché
